using System.Collections;
using System;
using System.Collections.Generic;
using UnityEngine;
using Unity.VisualScripting;

public class GameInput : MonoBehaviour
{
    private PlayerInputAction playerinputaction;
    public event EventHandler OnInteraction;
    public event EventHandler OnInteractAlternateAction;
    private void Awake()
    {
         playerinputaction =new PlayerInputAction();
         playerinputaction.Player.Enable();
         playerinputaction.Player.Interact.performed += Interact_performed;
         playerinputaction.Player.InteractAlternate.performed += InteractAlernate_performed;
    }
    private void InteractAlernate_performed(UnityEngine.InputSystem.InputAction.CallbackContext obj)
    {
        OnInteractAlternateAction?.Invoke(this, EventArgs.Empty);
    }
    private void Interact_performed(UnityEngine.InputSystem.InputAction.CallbackContext obj)
    {
        OnInteraction?.Invoke(this, EventArgs.Empty);      /// it is action event *automaticvally generated by tab
    }

    public Vector2 GetMovementNormalized()
    {
        Vector2 inputVector = playerinputaction.Player.Move.ReadValue<Vector2>();

       
        inputVector = inputVector.normalized; //use to noramlize the condition in which the vector become (1,1) and the charactere move at high magnitude ay diagopnal
        return inputVector;
    }
     
}
